USE [master]
GO

/****** Object:  Database [LiftInstallationDataDB]    Script Date: 26/11/2018 5:44:15 PM ******/
CREATE DATABASE [LiftInstallationDataDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LiftInstallationDataDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\LiftInstallationDataDB.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LiftInstallationDataDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\LiftInstallationDataDB_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LiftInstallationDataDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LiftInstallationDataDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LiftInstallationDataDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LiftInstallationDataDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LiftInstallationDataDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LiftInstallationDataDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LiftInstallationDataDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LiftInstallationDataDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LiftInstallationDataDB] SET  MULTI_USER 
GO

ALTER DATABASE [LiftInstallationDataDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LiftInstallationDataDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LiftInstallationDataDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LiftInstallationDataDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LiftInstallationDataDB] SET  READ_WRITE 
GO

