//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJIP_LIMMV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorBoxInfo
    {
        public int ID { get; set; }
        public string TownCouncil { get; set; }
        public int BlockNo { get; set; }
        public string LiftNo { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string SIMCard { get; set; }
        public string LMPD { get; set; }
    }
}
